services:
  postgres:
    image: postgres:14.4-alpine
    container_name: DMITRII
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER:  "USER"
      POSTGRES_DB:  "WB"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nats:
    image: nats:2.8-alpine
    container_name: NATS
    command: -js -sd /data
    volumes:
      - nats:/data
    ports:
      - 4222:4222

volumes:
  postgres:
  nats:

